

# EBS
sqry <- "SELECT HAEHNR.BIOMASS_EBS_PLUSNW.SPECIES_CODE, 
HAEHNR.BIOMASS_EBS_PLUSNW.COMMON_NAME, 
HAEHNR.BIOMASS_EBS_PLUSNW.YEAR, 
HAEHNR.BIOMASS_EBS_PLUSNW.STRATUM, 
HAEHNR.BIOMASS_EBS_PLUSNW.BIOMASS, 
HAEHNR.BIOMASS_EBS_PLUSNW.VARBIO, 
HAEHNR.BIOMASS_EBS_PLUSNW.LOWERB, 
HAEHNR.BIOMASS_EBS_PLUSNW.UPPERB
FROM HAEHNR.BIOMASS_EBS_PLUSNW
WHERE (((HAEHNR.BIOMASS_EBS_PLUSNW.SPECIES_CODE) in (21740, 21741, 21720, 10110, 10210, 10130, 10261, 10285))) AND
STRATUM between 1 AND 6"

# NBS
sqry <- "SELECT HAEHNR.BIOMASS_NBS_SAFE.SPECIES_CODE, 
HAEHNR.BIOMASS_NBS_SAFE.COMMON_NAME, 
HAEHNR.BIOMASS_NBS_SAFE.YEAR, 
HAEHNR.BIOMASS_NBS_SAFE.STRATUM, 
HAEHNR.BIOMASS_NBS_SAFE.BIOMASS, 
HAEHNR.BIOMASS_NBS_SAFE.VARBIO, 
HAEHNR.BIOMASS_NBS_SAFE.LOWERB, 
HAEHNR.BIOMASS_NBS_SAFE.UPPERB
FROM HAEHNR.BIOMASS_NBS_SAFE
WHERE (((HAEHNR.BIOMASS_NBS_SAFE.SPECIES_CODE) in (21740, 21741, 21720, 10110, 10210, 10130, 10261, 10285))) AND
STRATUM = 999"
